version: "3.0"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_DB: practice
    ports:
      - "5432:5432"
  server:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
